meta:
  url:
  title:
  description:
  siteName:
  sns: ['twitter']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: ['line-numbers']
    languages: ['javascript', 'html']
    css: true
    theme: twilight # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
